import os
from dotenv import load_dotenv

load_dotenv()

TARGET_TWITTER_POST_START_UNIX_MILLISECOND = 1717729500000
TARGET_TWITTER_POST_END_UNIX_MILLISECOND = 1717729610000

# Extractで何日前のデータを最新と定義するか。開発中は3日前が楽。
COMMUNITY_NOTE_DAYS_AGO = 3

X_BEARER_TOKEN = os.getenv("X_BEARER_TOKEN")
