"""notes and posts

Revision ID: 1f33aeb4bebf
Revises:
Create Date: 2025-02-22 16:16:44.777479

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f33aeb4bebf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("link_id"),
    )
    op.create_index(op.f("ix_links_url"), "links", ["url"], unique=False)
    op.create_table(
        "media",
        sa.Column("media_key", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("photo", "video", "animated_gif", native_enum=False), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("width", sa.DECIMAL(), nullable=False),
        sa.Column("height", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("media_key"),
    )
    op.create_table(
        "notes",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("note_id"),
    )
    op.create_table(
        "row_users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("profile_image_url", sa.String(), nullable=False),
        sa.Column("followers_count", sa.DECIMAL(), nullable=False),
        sa.Column("following_count", sa.DECIMAL(), nullable=False),
        sa.Column("tweet_count", sa.DECIMAL(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_type", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "topics",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("topic_id"),
    )
    op.create_table(
        "x_users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("profile_image", sa.String(), nullable=False),
        sa.Column("followers_count", sa.DECIMAL(), nullable=False),
        sa.Column("following_count", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "note_topic",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.note_id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.topic_id"],
        ),
        sa.PrimaryKeyConstraint("note_id", "topic_id"),
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", sa.DECIMAL(), nullable=False),
        sa.Column("like_count", sa.DECIMAL(), nullable=False),
        sa.Column("repost_count", sa.DECIMAL(), nullable=False),
        sa.Column("impression_count", sa.DECIMAL(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["x_users.user_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "row_posts",
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", sa.DECIMAL(), nullable=False),
        sa.Column("like_count", sa.DECIMAL(), nullable=False),
        sa.Column("repost_count", sa.DECIMAL(), nullable=False),
        sa.Column("bookmark_count", sa.DECIMAL(), nullable=False),
        sa.Column("impression_count", sa.DECIMAL(), nullable=False),
        sa.Column("quote_count", sa.DECIMAL(), nullable=False),
        sa.Column("reply_count", sa.DECIMAL(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["row_users.user_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "post_link",
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["links.link_id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "link_id"),
    )
    op.create_table(
        "post_media",
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("media_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_key"],
            ["media.media_key"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "media_key"),
    )
    op.create_table(
        "row_notes",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("note_author_participant_id", sa.String(), nullable=False),
        sa.Column("created_at_millis", sa.DECIMAL(), nullable=False),
        sa.Column("tweet_id", sa.String(), nullable=False),
        sa.Column("believable", sa.CHAR(), nullable=False),
        sa.Column("misleading_other", sa.CHAR(), nullable=False),
        sa.Column("misleading_factual_error", sa.CHAR(), nullable=False),
        sa.Column("misleading_manipulated_media", sa.CHAR(), nullable=False),
        sa.Column("misleading_outdated_information", sa.CHAR(), nullable=False),
        sa.Column("misleading_missing_important_context", sa.CHAR(), nullable=False),
        sa.Column("misleading_unverified_claim_as_fact", sa.CHAR(), nullable=False),
        sa.Column("misleading_satire", sa.CHAR(), nullable=False),
        sa.Column("not_misleading_other", sa.CHAR(), nullable=False),
        sa.Column("not_misleading_factually_correct", sa.CHAR(), nullable=False),
        sa.Column("not_misleading_outdated_but_not_when_written", sa.CHAR(), nullable=False),
        sa.Column("not_misleading_clearly_satire", sa.CHAR(), nullable=False),
        sa.Column("not_misleading_personal_opinion", sa.CHAR(), nullable=False),
        sa.Column("trustworthy_sources", sa.CHAR(), nullable=False),
        sa.Column("is_media_note", sa.CHAR(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("not_misleading", "misinformed_or_potentially_misleading", name="notesclassification"),
            nullable=False,
        ),
        sa.Column("harmful", sa.Enum("little_harm", "considerable_harm", "empty", name="notesharmful"), nullable=False),
        sa.Column("validation_difficulty", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("row_post_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["row_post_id"],
            ["row_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
    )
    op.create_table(
        "row_post_embed_urls",
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("expanded_url", sa.String(), nullable=False),
        sa.Column("unwound_url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["row_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "url"),
    )
    op.create_table(
        "row_post_media",
        sa.Column("media_key", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("photo", "video", "animated_gif", native_enum=False), nullable=False),
        sa.Column("width", sa.DECIMAL(), nullable=False),
        sa.Column("height", sa.DECIMAL(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["row_posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("media_key"),
        sa.UniqueConstraint("media_key"),
    )
    op.create_table(
        "row_note_status",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("note_author_participant_id", sa.String(), nullable=False),
        sa.Column("created_at_millis", sa.DECIMAL(), nullable=False),
        sa.Column("timestamp_millis_of_first_non_n_m_r_status", sa.DECIMAL(), nullable=True),
        sa.Column("first_non_n_m_r_status", sa.String(), nullable=True),
        sa.Column("timestamp_millis_of_current_status", sa.DECIMAL(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("timestamp_millis_of_latest_non_n_m_r_status", sa.DECIMAL(), nullable=True),
        sa.Column("most_recent_non_n_m_r_status", sa.String(), nullable=True),
        sa.Column("timestamp_millis_of_status_lock", sa.DECIMAL(), nullable=True),
        sa.Column("locked_status", sa.String(), nullable=True),
        sa.Column("timestamp_millis_of_retro_lock", sa.DECIMAL(), nullable=True),
        sa.Column("current_core_status", sa.String(), nullable=True),
        sa.Column("current_expansion_status", sa.String(), nullable=True),
        sa.Column("current_group_status", sa.String(), nullable=True),
        sa.Column("current_decided_by", sa.String(), nullable=True),
        sa.Column("current_modeling_group", sa.Integer(), nullable=True),
        sa.Column("timestamp_millis_of_most_recent_status_change", sa.DECIMAL(), nullable=True),
        sa.Column("timestamp_millis_of_nmr_due_to_min_stable_crh_time", sa.DECIMAL(), nullable=True),
        sa.Column("current_multi_group_status", sa.String(), nullable=True),
        sa.Column("current_modeling_multi_group", sa.Integer(), nullable=True),
        sa.Column("timestamp_minute_of_final_scoring_output", sa.DECIMAL(), nullable=True),
        sa.Column("timestamp_millis_of_first_nmr_due_to_min_stable_crh_time", sa.DECIMAL(), nullable=True),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["row_notes.note_id"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("row_note_status")
    op.drop_table("row_post_media")
    op.drop_table("row_post_embed_urls")
    op.drop_table("row_notes")
    op.drop_table("post_media")
    op.drop_table("post_link")
    op.drop_table("row_posts")
    op.drop_table("posts")
    op.drop_table("note_topic")
    op.drop_table("x_users")
    op.drop_table("topics")
    op.drop_table("row_users")
    op.drop_table("notes")
    op.drop_table("media")
    op.drop_index(op.f("ix_links_url"), table_name="links")
    op.drop_table("links")
    # ### end Alembic commands ###
