"""add metrics to note

Revision ID: 429176092448
Revises: 1f33aeb4bebf
Create Date: 2025-09-07 14:56:23.850062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429176092448'
down_revision: Union[str, None] = '1f33aeb4bebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('has_been_helpfuled', sa.Boolean(), nullable=False))
    op.add_column('notes', sa.Column('helpful_count', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('not_helpful_count', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('somewhat_helpful_count', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('current_status_history', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'current_status_history')
    op.drop_column('notes', 'somewhat_helpful_count')
    op.drop_column('notes', 'not_helpful_count')
    op.drop_column('notes', 'helpful_count')
    op.drop_column('notes', 'has_been_helpfuled')
    # ### end Alembic commands ###
