"""add metrics columns

Revision ID: bf8979a8a8dc
Revises: 1f33aeb4bebf
Create Date: 2025-09-07 18:10:16.564601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8979a8a8dc'
down_revision: Union[str, None] = '1f33aeb4bebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # note_author_participant_idをnullableにして、既存データとの互換性を保つ
    op.add_column('notes', sa.Column('note_author_participant_id', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('has_been_helpfuled', sa.Boolean(), nullable=True))
    op.add_column('notes', sa.Column('rate_count', sa.DECIMAL(), nullable=True))
    op.add_column('notes', sa.Column('helpful_count', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('not_helpful_count', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('somewhat_helpful_count', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('current_status_history', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('aggregated_at', sa.DECIMAL(), nullable=True))
    # 制約名を明示的に指定
    op.create_unique_constraint('uq_row_post_media_media_key', 'row_post_media', ['media_key'])
    op.add_column('row_posts', sa.Column('aggregated_at', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row_posts', 'aggregated_at')
    op.drop_constraint('uq_row_post_media_media_key', 'row_post_media', type_='unique')
    op.drop_column('posts', 'aggregated_at')
    op.drop_column('notes', 'current_status_history')
    op.drop_column('notes', 'somewhat_helpful_count')
    op.drop_column('notes', 'not_helpful_count')
    op.drop_column('notes', 'helpful_count')
    op.drop_column('notes', 'rate_count')
    op.drop_column('notes', 'has_been_helpfuled')
    op.drop_column('notes', 'note_author_participant_id')
    # ### end Alembic commands ###
