"""Test

Revision ID: c356b162f2f7
Revises: add_language_to_row_notes
Create Date: 2025-06-29 09:00:09.771045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c356b162f2f7'
down_revision: Union[str, None] = 'add_language_to_row_notes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # test カラムは存在しない可能性があるため、削除をスキップ
    # op.drop_column('notes', 'test')
    op.add_column('row_posts', sa.Column('extracted_at', sa.DECIMAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row_posts', 'extracted_at')
    op.add_column('notes', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
