FROM public.ecr.aws/lambda/python:3.12

# 作業ディレクトリを設定
WORKDIR ${LAMBDA_TASK_ROOT}

RUN dnf update -y && \
    dnf install -y gcc gcc-c++ git && \
    dnf clean all && \
    rm -rf /var/cache/dnf

COPY etl/. .

RUN python -m pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -e .[prod]

# Lambda関数のコードをコピー
COPY etl/src/birdxplorer_etl/lib/lambda_handler/postlookup_lambda.py ./

# Lambda handler を設定
CMD ["postlookup_lambda.lambda_handler"]