# AWS Lambda Container Image用のDockerfile
FROM public.ecr.aws/lambda/python:3.10

# 作業ディレクトリを設定
WORKDIR ${LAMBDA_TASK_ROOT}

RUN yum update -y && \
    yum install -y postgresql-devel gcc git && \
    yum clean all

COPY etl/. .

RUN python -m pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -e .[prod]

# Lambda関数のコードをコピー
COPY etl/src/birdxplorer_etl/lib/x/postlookup_lambda.py ./

# Lambda関数のハンドラーを指定
CMD ["postlookup_lambda.lambda_handler"]
