name: Project test
on: push

permissions:
  contents: read
  packages: read

jobs:
  test-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: birdxplorer
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: dependency install
        run: pip install -e ".[dev]"
      - name: copy env
        run: cp .env.example .env
      - name: test
        run: tox
