name: Project test
on: push

permissions:
  contents: read
  packages: read

jobs:
  test-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: dependency install
        run: pip install -e ".[dev]"
      - name: test
        run: tox
